### ISSUE TITLE
"UnicodeEncodeError: 'cp932' codec can't encode character '\xd6' in position 17: illegal multibyte sequence"

### ISSUE THREAD

**Issue by VNLoverMay** [Logg-y/magicgen#6]
Had this error show up while using the GUI version. Haven't manually touched any files. Not sure why this is happening, so I figured I'd come here and drop an issue report to see if it can be reproduced. Dropping the full log, including my parameters, below.
```
Passing parameters: ['E:\\Dom5Gen\\MagicGen\\magicgen.exe', '-run', '1', '-nationlist', '120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169', '-spellsperlevel', '14', '-constructionfactor', '0.6', '-modlist', 'E:\\Dom5Gen\\NationGen\\mods\\nationgen_molten_minaret.dm\n', '-nationalspells', '12', '-samepathsecondarychance', '40', '-summonsamepathsecondarychance', '40', '-summondiffpathsecondarychance', '10', '-researchmodifier', '0', '-fatiguemodflat', '0', '-fatiguemodmult', '1.0', '-pathlevelmodflat', '0', '-pathlevelmodmult', '1.0', '-outputfolder', 'E:\\Dom5Gen\\MagicGen\\output', '-unitidstart', '4694', '-spellidstart', '1404', '-weaponidstart', '916', '-siteidstart', '1581', '-montagidstart', '1006', '-diffpathsecondarychance', '10', '-eventcodestart', '-300', '-montagscale', '1.5', '-clearvanillanationalspells', '0', '-clearvanillagenericspells', '1', '-bloodcostscale', '1.0', '-nobadaispells', '0']
Parsing data files...
Generating 14 spells at research 4 for school CONJURATION (70 remain)...
Generating 14 spells at research 0 for school ENCHANTMENT (69 remain)...
No more valid effects at research 0 for school ENCHANTMENT, generated 10/14 successfully
Generating 8 spells at research 7 for school CONSTRUCTION (68 remain)...
Generating 14 spells at research 7 for school THAUMATURGY (67 remain)...
Generating 14 spells at research 7 for school CONJURATION (66 remain)...
Generating 14 spells at research 8 for school ENCHANTMENT (65 remain)...
Generating 14 spells at research 6 for school CONJURATION (64 remain)...
Generating 14 spells at research 8 for school ALTERATION (63 remain)...
Generating 14 spells at research 7 for school EVOCATION (62 remain)...
Generating 14 spells at research 6 for school EVOCATION (61 remain)...
Generating 14 spells at research 6 for school BLOOD (60 remain)...
Generating 8 spells at research 9 for school CONSTRUCTION (59 remain)...
Generating 14 spells at research 4 for school EVOCATION (58 remain)...
Generating 14 spells at research 0 for school CONJURATION (57 remain)...
No more valid effects at research 0 for school CONJURATION, generated 5/14 successfully
Generating 14 spells at research 6 for school THAUMATURGY (56 remain)...
Generating 14 spells at research 0 for school EVOCATION (55 remain)...
No more valid effects at research 0 for school EVOCATION, generated 13/14 successfully
Generating 14 spells at research 4 for school BLOOD (54 remain)...
Generating 14 spells at research 9 for school ALTERATION (53 remain)...
Generating 14 spells at research 1 for school ENCHANTMENT (52 remain)...
Generating 14 spells at research 5 for school EVOCATION (51 remain)...
Generating 14 spells at research 1 for school ALTERATION (50 remain)...
Generating 8 spells at research 0 for school CONSTRUCTION (49 remain)...
No more valid effects at research 0 for school CONSTRUCTION, generated 0/8 successfully
Generating 8 spells at research 1 for school CONSTRUCTION (48 remain)...
No more valid effects at research 1 for school CONSTRUCTION, generated 2/8 successfully
Generating 14 spells at research 8 for school CONJURATION (47 remain)...
Generating 14 spells at research 2 for school CONJURATION (46 remain)...
Generating 14 spells at research 9 for school THAUMATURGY (45 remain)...
Generating 14 spells at research 4 for school ENCHANTMENT (44 remain)...
Generating 14 spells at research 3 for school ENCHANTMENT (43 remain)...
Generating 14 spells at research 3 for school ALTERATION (42 remain)...
Generating 14 spells at research 5 for school THAUMATURGY (41 remain)...
Generating 14 spells at research 5 for school ALTERATION (40 remain)...
Generating 14 spells at research 9 for school BLOOD (39 remain)...
Generating 14 spells at research 4 for school ALTERATION (38 remain)...
Generating 14 spells at research 3 for school BLOOD (36 remain)...
Generating 14 spells at research 5 for school BLOOD (35 remain)...
Generating 14 spells at research 7 for school ALTERATION (34 remain)...
Generating 14 spells at research 2 for school EVOCATION (33 remain)...
Generating 14 spells at research 2 for school BLOOD (32 remain)...
No more valid effects at research 2 for school BLOOD, generated 11/14 successfully
Generating 14 spells at research 0 for school BLOOD (31 remain)...
No more valid effects at research 0 for school BLOOD, generated 0/14 successfully
Generating 14 spells at research 0 for school ALTERATION (30 remain)...
Generating 14 spells at research 8 for school EVOCATION (28 remain)...
Generating 14 spells at research 2 for school ENCHANTMENT (27 remain)...
Generating 14 spells at research 1 for school EVOCATION (26 remain)...
Generating 14 spells at research 3 for school CONJURATION (25 remain)...
Generating 14 spells at research 8 for school BLOOD (24 remain)...
Generating 14 spells at research 3 for school THAUMATURGY (23 remain)...
Generating 14 spells at research 5 for school ENCHANTMENT (22 remain)...
Generating 8 spells at research 3 for school CONSTRUCTION (20 remain)...
Generating 14 spells at research 0 for school THAUMATURGY (19 remain)...
No more valid effects at research 0 for school THAUMATURGY, generated 10/14 successfully
Generating 14 spells at research 1 for school CONJURATION (18 remain)...
Generating 14 spells at research 4 for school THAUMATURGY (17 remain)...
Generating 14 spells at research 7 for school ENCHANTMENT (16 remain)...
Generating 14 spells at research 8 for school THAUMATURGY (15 remain)...
Generating 14 spells at research 9 for school EVOCATION (14 remain)...
Generating 14 spells at research 2 for school THAUMATURGY (13 remain)...
Generating 8 spells at research 5 for school CONSTRUCTION (11 remain)...
Generating 14 spells at research 1 for school BLOOD (10 remain)...
No more valid effects at research 1 for school BLOOD, generated 3/14 successfully
Generating 14 spells at research 7 for school BLOOD (9 remain)...
Generating 14 spells at research 2 for school ALTERATION (8 remain)...
Generating 14 spells at research 1 for school THAUMATURGY (7 remain)...
Generating 14 spells at research 9 for school ENCHANTMENT (6 remain)...
Generating 14 spells at research 6 for school ALTERATION (5 remain)...
Generating 14 spells at research 3 for school EVOCATION (4 remain)...
Generating 14 spells at research 5 for school CONJURATION (3 remain)...
Generating 14 spells at research 6 for school ENCHANTMENT (2 remain)...
Generating 14 spells at research 9 for school CONJURATION (1 remain)...
Generating holy spells...
Reading vanilla nations
Finished reading vanilla nations
Reading mod nations
Traceback (most recent call last):
File "D:\Python38\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 74, in run
File "D:\Python38\lib\site-packages\cx_Freeze\initscripts\Console.py", line 36, in run
File "magicgen.py", line 782, in <module>
File "magicgen.py", line 760, in main
File "magicgen.py", line 248, in rollspells
File "D:\Python38\Lib\site-packages\dom\magicgen\fileparser\nationals.py", line 249, in read_mods
UnicodeEncodeError: 'cp932' codec can't encode character '\xd6' in position 17: illegal multibyte sequence
```

A bit more info: This is for a 50 nations nationgen mod, with national generation for vanilla nations disabled. Other than that, settings should be bog standard. This could be a nationgen issue, but the game doesn't throw any errors and works fine - so I'm posting it here first.

**Comment by Logg-y** [comment]
It's an encoding issue caused by the nationgen .dm file, specifically the character Ö (0xd6). If you made a copy of the .dm and replaced all instances of this with something else it would probably work for the purposes of feeding into magicgen to generate national spells.

I'll look into this and try to give it a proper fix, but this workaround should hopefully let you generate spells at the very least.

I am also not sure why the file output is defaulting to cp932, but this may have something to do with your OS language settings. Changing it to something English or European which contains this character might also help. I'll add something to try to force the encoding of the output to something that should play a bit nicer.

**Comment by Logg-y** [comment]
Put in a change that hopefully addresses this for the next update.
